version: '2'

services:

  mongo:
    build: mongo/
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  super-simple-auth:
    build: super-simple-auth/
    depends_on:
      - mongo
    command: bash /usr/src/start
    ports:
      - "3000:3000"
    volumes:
      - ./super-simple-auth:/usr/src
    environment:
      - AUTH_SECRET=MySecret
      - AUTH_SMTP_EMAIL=MyEmail
      - AUTH_SMTP_PASSWORD=MyPassword
      - AUTH_SMTP_HOST=MyHost
      - PORT=3000
